# my global config
global:
  scrape_interval: 5s 
  
# Set the scrape interval to every 15 seconds. Default is every 1 minute.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  
  - job_name: 'API-GATEWAY-MONITOR'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs: 
    - targets: ['localhost:8080']
  
  - job_name: 'USER-MANAGER-MONITOR'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs: 
    - targets: ['localhost:8081']

  - job_name: 'EMAIL-SENDER-MONITOR'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs: 
    - targets: ['localhost:8082', 'localhost:8083']

  - job_name: 'EUREKA-REGISTRY-MONITOR'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs: 
    - targets: ['localhost:8761']
